Repository tigraph/tidb, pull requests merged in 2022-01, with the labels that each got.

#9 codec: support graph
  ddl/ddl_api.go
  executor/batch_point_get.go
  executor/point_get.go
  executor/write_test.go
  table/tables/graph.go
  table/tables/tables.go
  tablecodec/tablecodec.go
Labels: sig/execution, sig/sql-infra

#14 executor: finish GraphEdgeScanExecutor
  ddl/ddl_api.go
  executor/builder.go
  executor/graph.go
  tablecodec/tablecodec.go
Labels: sig/execution, sig/sql-infra

#17 planner: prune destination columns if destination is not specified
  executor/graph.go
  planner/core/logical_plan_builder.go
  planner/core/rule_column_pruning.go
Labels: sig/execution

#19 ddl: support alter column add graph option
  ddl/column.go
  ddl/ddl_api.go
  ddl/ddl_worker.go
  parser/model/ddl.go
  planner/core/rule_column_pruning.go
Labels: sig/sql-infra

#20 executor,planner: graph support match any shortest
  executor/builder.go
  executor/graph_shortest.go
  planner/core/exhaust_physical_plans.go
  planner/core/initialize.go
  planner/core/logical_plan_builder.go
  planner/core/logical_plans.go
  planner/core/physical_plans.go
  planner/core/rule_column_pruning.go
  planner/core/task.go
  util/plancodec/id.go
Labels: sig/execution, sig/planner
